version: '3'

services:
  event_db:
    image: mysql:5.7
    restart: always
    container_name: eventDbContainer
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wsit_event_db
    ports:
      - "6607:3306"
    volumes:
      - "db-data:/var/lib/mysql"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eventBackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
    - event_db

volumes:
  db-data: