from django.conf.urls import url

from app.views import common_views, matching, export_import_view, export_lambda, login_view, hotel_view, attendee_view, \
    question_view, room_view, location_view, session_views, setting_view, scan_view, photo_reel, message_view, \
    datatable, travel_view, admin_view, menu_view, page_view, style_view, template_view, attendee_datatable, \
    reset_password, checkpoint_view, file_view, \
    checkpoint_datatable, language_view, email_view, deleted_history, dashboard, update_database, language_default_view, \
    economy_view, payment_view
from publicfront.views import socket
from .views import filter

urlpatterns = [
    url(r'^admin/$', admin_view.AdminView.as_view(), name="admin"),
    url(r'^admins/(?P<pk>[0-9]+)/$', admin_view.AdminDetailView.as_view(), name='adminDetails'),
    url(r'^admin-search/$', admin_view.AdminView.admin_search, name='admin-search'),
    url(r'^admin-change-status/$', admin_view.AdminView.change_status, name='admin-change-status'),
    url(r'^admin-render-permission-eventwise/$', admin_view.AdminView.render_permission,
        name='admin-render-permission-eventwise'),

    url(r'^$', common_views.IndexView.as_view(), name='index'),
    url(r'^access/login/$', login_view.Login.as_view(), name='login'),
    url(r'^access/logout/$', login_view.LogoutView.as_view(), name='logout'),
    # url(r'^access/forgot-password/$', views.LoginView.as_view(), name='forgot_password'),

    url(r'^hotels/$', hotel_view.HotelView.as_view(), name='hotels'),
    url(r'^hotels/show/$', hotel_view.HotelListView.as_view(), name="hotelList"),
    url(r'^hotels/add/$', hotel_view.HotelView.add, name='addHotels'),
    url(r'^hotels/edit/$', hotel_view.HotelView.edit, name='editHotels'),
    url(r'^hotels/match/$', hotel_view.HotelView.match, name='matchHotels'),
    url(r'^hotels/match-partial/$', hotel_view.HotelView.match_partial, name='matchHotelsPartial'),
    url(r'^hotels/match/pairup/$', hotel_view.HotelView.pair_up, name='pair_up'),
    url(r'^hotels/match/breakup/$', hotel_view.HotelView.break_up, name='break_up'),
    url(r'^hotels/(?P<pk>[0-9]+)/$', hotel_view.HotelDetailView.as_view(), name='hotelDetail'),
    url(r'^hotels/delete/$', hotel_view.HotelView.delete, name='deleteHotel'),
    url(r'^hotel-search/$', hotel_view.HotelView.search, name='searchHotel'),
    url(r'^hotels/check-match/$', hotel_view.HotelView.check_match, name='check-match'),
    url(r'^hotels/export-allotment-report/$', hotel_view.HotelView.generate_hotel_report_excel,
        name='export-hotels-allotment-report'),

    url(r'^questions/$', question_view.QuestionView.as_view(), name='questions'),
    url(r'^questions/show/$', question_view.QuestionListView.as_view(), name="questionList"),
    url(r'^questions/(?P<pk>[0-9]+)/$', question_view.QuestionDetailView.as_view(), name='questionDetail'),
    url(r'^questions/delete/$', question_view.QuestionView.delete, name='deleteQuestion'),
    url(r'^questions/all/$', question_view.QuestionView.getAllQuestions, name='allQuestions'),
    url(r'^questions/question_order/$', question_view.QuestionView.set_questions_order, name='order-question'),
    url(r'^question-search/$', question_view.QuestionView.search, name='searchQuestion'),
    url(r'^options/delete/$', question_view.QuestionView.delete_option, name='deleteOption'),
    url(r'^questions/option/$', question_view.QuestionView.get_questions_option, name='question-options'),
    url(r'^questions/all-options/$', question_view.QuestionView.get_questions_all_option, name='question-all-options'),
    url(r'^questions/option-order/$', question_view.QuestionView.option_order, name='question-option-order'),
    url(r'^questions/duplicate/$', question_view.QuestionView.question_duplicate, name='question-duplicate'),

    url(r'^locations/$', location_view.LocationView.as_view(), name='locations'),
    url(r'^locations/(?P<pk>[0-9]+)/$', location_view.LocationDetailView.as_view(), name='locationDetail'),
    url(r'^locations/delete/$', location_view.LocationView.delete, name='locationDelete'),
    url(r'^location-search/$', location_view.LocationView.search, name='searchLocation'),
    url(r'^locations/duplicate/$', location_view.LocationView.location_duplicate, name='location-duplicate'),
    url(r'^locations/location_order/$', location_view.LocationView.set_locations_order, name='order-location'),

    url(r'^settings/$', setting_view.SettingView.as_view(), name='settings'),
    url(r'^settings/delete/$', setting_view.SettingView.delete, name='deleteGroup'),
    url(r'^groups_order/$', setting_view.SettingView.set_groups_order, name='setGroupsOrder'),
    url(r'^notification-settings/$', setting_view.SettingView.notificationTimeout, name='notification-settings'),
    url(r'^settings/settings-attendee-global-details/$', setting_view.SettingView.get_settings_attendee_global_details,
        name='settings-attendee-global-details'),

    url(r'^attendee/$', attendee_view.AttendeeView.as_view(), name="attendee"),
    url(r'^attendee/users/$', datatable.AttendeeListView.as_view(), name="attendeeList"),
    url(r'^attendee/userlist/$', attendee_datatable.AttendeeListView.as_view(), name="attendeeUserList"),
    url(r'^attendee/(?P<pk>[0-9]+)/$', attendee_view.AttendeeDetailView.as_view(), name='attendeeDetail'),
    url(r'^attendee-info/(?P<pk>[0-9]+)/$', attendee_view.AttendeeDetailView.attendeeInfo, name='attendeeInfo'),
    url(r'^attendee/default-answer/$', attendee_view.AttendeeDetailView.default_answer, name='defaultAnswer'),
    url(r'^attendee/delete/$', attendee_view.AttendeeView.delete, name='deleteAttendee'),
    url(r'^attendee/reset/$', attendee_view.AttendeeView.resetAttendee, name='resetAttendee'),
    url(r'^attendee/activity/(?P<user_id>[0-9]+)/$', attendee_view.AttendeeDetailView.get_history,
        name='activityAttendee'),
    url(r'^attendee/group-activity/(?P<user_id>[0-9]+)/$',
        attendee_view.GroupRegistrationDetail.get_group_registrations,
        name='groupactivityAttendee'),
    url(r'^attendee/group-registration-attendee-search/$',
        attendee_view.GroupRegistrationDetail.get_group_registration_attendee_search,
        name='group-registration-attendee-search'),
    url(r'^attendee/add-group-registration-attendee/$',
        attendee_view.GroupRegistrationDetail.add_group_registration_attendee,
        name='add-group-registration-attendee'),
    url(r'^attendee/delete-group-registration-attendee/$',
        attendee_view.GroupRegistrationDetail.delete_group_registration_attendee,
        name='delete-group-registration-attendee'),
    url(r'^attendee/sessions/(?P<user_id>[0-9]+)/$', attendee_view.AttendeeDetailView.get_sessions,
        name='sessionsAttendee'),
    url(r'^attendee/hotels/(?P<user_id>[0-9]+)/$', attendee_view.AttendeeDetailView.get_hotels, name='hotelsAttendee'),
    url(r'^attendee/travels/(?P<user_id>[0-9]+)/$', attendee_view.AttendeeDetailView.get_travels,
        name='travelsAttendee'),

    url(r'^attendee/getattendees/$', attendee_view.AttendeeView.get_attendees, name='get_attendees'),
    url(r'^attendee/gettags/$', common_views.TagView.get_tags, name='get_tags'),
    url(r'^attendee/secret_key_validation/$', attendee_view.AttendeeView.check_unique_secret_key,
        name='checkUuniqueSecretKey'),

    url(r'^attendee/getspeakers/$', attendee_view.AttendeeView.get_speakers, name='getSpeaker'),
    url(r'^attendee/(?P<user_id>[0-9]+)/attendee-orders/$', attendee_view.AttendeeView.attendee_order,
        name='getAttendeeOrders'),
    url(r'^attendee/(?P<user_id>[0-9]+)/group-orders/$', attendee_view.AttendeeView.group_order, name='getGroupOrders'),
    url(r'^attendee/(?P<user_id>[0-9]+)/balance/$', attendee_view.AttendeeView.attendee_balance,
        name='getAttendeeBalance'),
    url(r'^attendee/change-order-status/$', attendee_view.AttendeeView.change_order_status, name='changeOrderStatus'),
    url(r'^attendee/add-rebate-to-order/$', attendee_view.AttendeeView.add_rebate_to_order, name='addRebateToOrder'),
    url(r'^attendee/remove-rebate-from-order/$', attendee_view.AttendeeView.remove_rebate_from_order,
        name='removeRebateFromOrder'),
    url(r'^attendee/change-order-item-cost/$', attendee_view.AttendeeView.change_order_item_cost, name='changeOrderItemCost'),

    url(r'^attendee_session/delete/$', attendee_view.AttendeeView.delete_session, name='deleteAttendeeSession'),
    url(r'^attendee_travel/delete/$', attendee_view.AttendeeView.delete_travel, name='deleteAttendeeTravel'),
    url(r'^attendee_booking/delete/$', attendee_view.AttendeeView.delete_booking, name='deleteAttendeeBooking'),
    url(r'^multiple_attendee/$', attendee_view.AttendeeView.get_multiple_attendee, name='getMultipleAttendee'),
    url(r'^update_multiple_attendee/$', attendee_view.AttendeeView.update_multiple_attendee,
        name='updateMultipleAttendee'),

    url(r'^answers/$', common_views.AnswerView.as_view(), name='answers'),

    url(r'^rooms/$', room_view.RoomView.as_view(), name='rooms'),
    url(r'^rooms/(?P<pk>[0-9]+)/$', room_view.RoomDetailView.as_view(), name='roomDetail'),
    url(r'^rooms/delete/$', room_view.RoomView.delete, name='deleteRoom'),
    url(r'^rooms_order/$', room_view.RoomView.set_rooms_order, name='setRoomsOrder'),

    url(r'^get_rooms_allotments/$', room_view.RoomView.find_booking, name='getRoomsAllotments'),

    url(r'^sessions/$', session_views.SessionView.as_view(), name='sessions'),
    url(r'^sessions/(?P<pk>[0-9]+)/$', session_views.SessionDetailView.as_view(), name='sessionsDetail'),
    url(r'^sessions/delete/$', session_views.SessionView.delete, name='deleteSession'),
    url(r'^sessions/remove-queue/$', session_views.SessionView.remove_queue, name='remove-queue'),
    url(r'^sessions/get-tags/$', session_views.SessionView.get_tags, name='get-tags'),
    url(r'^sessions/get-custom-class/$', session_views.SessionView.get_custom_class, name='get-custom-class'),
    url(r'^sessions/queue/$', session_views.SessionView.session_queue, name='session-queue'),
    url(r'^sessions/checkpoint/$', session_views.SessionView.session_checkpoint, name='session-checkpoint'),
    url(r'^sessions/move-queue/$', session_views.SessionView.session_move_queue, name='session-move-queue'),
    url(r'^sessions/attending/$', session_views.SessionView.session_attending, name='session-attending'),
    url(r'^sessions/pending/$', session_views.SessionView.session_deciding, name='session-pending'),
    url(r'^sessions/queue_order/$', session_views.SessionView.queue_order, name='session-queue-order'),
    url(r'^session-search/$', session_views.SessionView.session_search, name='session-search'),
    url(r'^sessions/duplicate/$', session_views.SessionView.session_duplicate, name='session-duplicate'),
    url(r'^forcefully-add-speaker/$', session_views.SessionView.addSpeakerFourcefullyToSession,
        name='session-forcefully-add-speaker'),
    url(r'^session-conflick-num/$', session_views.SessionView.session_conflick, name='session-conflick-num'),
    url(r'^remove-session-for-conflict/$', session_views.SessionView.session_remove_conflict,
        name='remove-session-for-conflict'),
    url(r'^sessions/session_order/$', session_views.SessionView.set_sessions_order, name='order-session'),
    url(r'^sessions/session-report/$', session_views.SessionView.generate_session_report_excel, name='session-report'),
    url(r'^sessions/visible-columns/$', session_views.SessionView.set_visible_columns, name='session-visible-columns'),
    url(r'^session/filter-status/$', session_views.SessionDetailView.session_filter_status,
        name='sessions-filter-status'),
    url(r'^session/filter-attending/$', session_views.SessionDetailView.session_filter_attending,
        name='sessions-filter-attending'),
    url(r'^session/filter-not-attending/$', session_views.SessionDetailView.session_filter_not_attending,
        name='sessions-filter-not-attending'),

    url(r'^sessions/create-temp-session-filter/$', session_views.SessionDetailView.create_temp_session_filter,
        name='create-temp-session-filter'),

    url(r'^description-preview/$', common_views.DescriptionView.show_description_preview, name='description-preview'),

    url(r'^filter/$', filter.FilterView.as_view(), name='filter'),
    url(r'^save_filter/$', filter.FilterView.save_filter, name='saveFilter'),
    url(r'^get_filter/$', filter.FilterView.get_filter, name='getFilter'),
    url(r'^filter/(?P<pk>[0-9]+)/$', filter.FilterDetailView.as_view(), name='filterDetail'),
    url(r'^filter/delete/$', filter.FilterView.delete, name='deleteFilter'),
    url(r'^filters/$', filter.FilterView.filters, name='filters'),
    url(r'^filter-search/$', filter.FilterView.search, name='searchFilter'),
    url(r'^filters/duplicate/$', filter.FilterView.filter_duplicate, name='filter-duplicate'),
    url(r'^filters/filter_order/$', filter.FilterView.set_filters_order, name='order-filter'),
    url(r'^filters/quick_filter_exists/$', filter.FilterView.quick_filter_exists, name='quick-filter-exists'),

    url(r'^allotment_delete/$', room_view.RoomView.delete_allotment, name='deleteAllotment'),
    url(r'^allotment_update/$', room_view.RoomView.update_allotment, name='updateAllotment'),
    url(r'^allotment_edit/$', room_view.RoomView.edit_allotment, name='editAllotment'),

    url(r'^event/$', common_views.EventView.as_view(), name='event'),
    url(r'^events/(?P<pk>[0-9]+)/$', common_views.EventDetailView.as_view(), name='eventDetails'),
    url(r'^events/delete/$', common_views.EventView.delete, name='event-delete'),
    url(r'^events/logged-in/$', common_views.EventView.attendee_logged_in, name='event-logged-in'),
    url(r'^events/logged-out/$', common_views.EventView.attendee_logged_out, name='event-logged-out'),
    url(r'^check-current-event/$', common_views.EventView.check_current_event, name='check-current-event'),

    url(r'^photo-reel/$', photo_reel.PhotoReelView.photo_admin_requested, name='photoAdminRequested'),
    url(r'^photo-reel-allowed/$', photo_reel.PhotoReelView.photo_admin_allowed, name='photoAdminAllowed'),
    url(r'^photo-reel-denied/$', photo_reel.PhotoReelView.photo_admin_denied, name='photoAdminDenied'),
    url(r'^photo-reel-all/$', photo_reel.PhotoReelView.photo_admin_all, name='photoAdminAll'),
    url(r'^photo-slider-duration/$', photo_reel.PhotoSliderDuration.as_view(), name='photo-slider-duration'),
    url(r'^change-photo-status/$', photo_reel.PhotoReelView.change_photo_status, name='changePhotoStatus'),
    url(r'^download-photo-reel/$', photo_reel.PhotoReelView.download_photo_reel, name='download-photo-reel'),
    url(r'^delete-photo/$', photo_reel.PhotoReelView.delete_photo, name='deletePhoto'),
    # url(r'^export-to-excel/$', export_import_view.ExcelView.attendeeList, name='export'),
    url(r'^import-from-excel/$', export_import_view.Uploader.upload, name='import'),
    # url(r'^import-from-excel/$', lambda_import.LambdaUpload.lambda_upload, name='import'),
    url(r'^import-status-check/$', export_import_view.Uploader.import_complete_status, name='import_status_check'),
    url(r'^render_import_change_page/(?P<pk>[0-9]+)/$', export_import_view.Uploader.render_import_status,
        name='render_import_change_page'),
    url(r'^import-hotel/$', export_import_view.ExcelView.hotel_import, name='importHotel'),

    url(r'^export-hotel/$', export_import_view.ExcelView.export_hotel, name='exportHotel'),

    url(r'^get-export-state/$', export_import_view.ExcelView.export_state, name='exportState'),

    url(r'^export-all/$', export_lambda.ExcelView.allExportList, name='allExportList'),
    url(r'^import-session/$', session_views.SessionView.importSession, name='importSession'),
    url(r'^export-session/$', export_import_view.ExcelView.export_session, name='exportSession'),
    url(r'^export-session/(?P<pk>[0-9]+)/$', export_import_view.ExcelView.export_session_by_id, name='exportSession'),
    # url(r'^export-session-settings/$', export_import_view.ExcelView.export_session_settings, name='export-session-settings'),
    url(r'^export-scanlist/$', export_import_view.ExcelView.export_scan_list, name='exportScan'),
    url(r'^export-secret/$', export_import_view.ExcelView.export_secret, name='exportSecret'),
    url(r'^export-ratings/$', export_import_view.ExcelView.export_ratings, name='exportRatings'),
    url(r'^export-filter/$', export_import_view.ExcelView.export_filters, name='exportFilters'),
    url(r'^get-export-html/$', export_import_view.ExcelView.get_modal_html, name='getModalHtml'),
    url(r'^export-filter/export/$', export_import_view.ExcelView.export, name='exportFiltersExport'),
    url(r'^export-filters/duplicate/$', export_import_view.ExcelView.filter_duplicate, name='export-filter-duplicate'),
    url(r'^export-filter/delete/$', export_import_view.ExcelView.delete, name='export-deleteFilter'),
    url(r'^export-filter/export_order/$', export_import_view.ExcelView.set_export_order, name='order-export'),
    url(r'^exported-files-list/$', export_import_view.ExcelView.exported_files_list, name='exported_files_list'),
    url(r'^download_exported-files/$', export_import_view.ExcelView.download_from_s3, name='downloadExportedFile'),
    url(r'^export_file/delete/$', export_import_view.ExcelView.delete_from_s3, name='deleteExportedFile'),
    url(r'^export-filter-search/$', export_import_view.ExcelView.search, name='export-filter-search'),
    url(r'^export-hotel-details/$', export_lambda.ExcelView.export_room_dependencies, name='export-hotel-details'),
    url(r'^import-list/$', export_import_view.ExcelView.approve_import_list, name='import-list'),
    url(r'^save-import/$', export_import_view.ExcelView.save_import, name='save-import'),
    url(r'^get-import-save-stats/$', export_import_view.ExcelView.get_import_state, name='get-import-save-stats'),
    url(r'^import-action/$', export_import_view.ExcelView.import_action, name='importAction'),
    url(r'^check-import-status/$', export_import_view.ExcelView.check_import_status, name='import-status'),
    url(r'^view-import/(?P<pk>[0-9]+)/$', export_import_view.ExcelView.view_approve_item, name='import-list'),
    url(r'^delete-import-changes/$', export_import_view.ExcelView.delete_approve_import_item,
        name='delete-import-item'),
    # url(r'^scan/$', scan_view.ScanView.as_view(), name='scan'),

    url(r'^checkpoints/$', checkpoint_view.CheckpointView.checkpoint_list, name='checkpoint'),
    url(r'^toggle-checkpoint-status/$', checkpoint_view.CheckpointView.change_status,
        name='toggle-checkpoint-status'),
    url(r'^change-checkpoint-status/$', checkpoint_view.CheckpointView.change_checkpoint_status,
        name='change-checkpoint-status'),
    url(r'^auto-perform-check/$', checkpoint_view.CheckpointView.auto_perform_check, name='auto-perform-check'),
    # url(r'^checkpoint-view/$', checkpoint_view.CheckpointView.checkpoint_attendee_table, name='checkpoint-attendee'),
    url(r'^checkpoints/(?P<pk>[0-9]+)/$', checkpoint_view.CheckpointView.checkpoint_details, name='checkpoint'),
    url(r'^add-checkpoint/$', checkpoint_view.CheckpointView.save_checkpoint, name='addCheckpoint'),
    url(r'^get-add-checkpoint-html/$', checkpoint_view.CheckpointView.get_modal_html, name='getCheckpointModalHtml'),
    url(r'^checkpoint/duplicate/$', checkpoint_view.CheckpointView.checkpoint_duplicate, name='checkpoint-duplicate'),
    url(r'^checkpoint/delete/$', checkpoint_view.CheckpointView.delete_checkpoint, name='checkpoint-delete'),
    url(r'^getcheckpointattendee/$', checkpoint_datatable.AttendeeListView.as_view(), name='getcheckpointattendee'),
    url(r'^export-checkpoint/$', checkpoint_view.CheckpointView.export_checkpoint, name='export-checkpoint'),
    url(r'^checkpoint-search/$', checkpoint_view.CheckpointView.search, name='checkpoint-search'),
    url(r'^checkpoint-update-manually/$', checkpoint_view.CheckpointView.checkpoint_manual_update,
        name='checkpoint-update-manually'),

    url(r'^travels/$', travel_view.TravelView.as_view(), name='travels'),
    url(r'^travels/(?P<pk>[0-9]+)/$', travel_view.TravelDetailView.as_view(), name='travelsDetail'),
    url(r'^travels/delete/$', travel_view.TravelView.delete, name='deleteTravel'),
    url(r'^travels/get-tags/$', travel_view.TravelView.get_tags, name='get-travel-tags'),
    url(r'^travel-search/$', travel_view.TravelView.travel_search, name='travel-search'),
    url(r'^travels/get-bound/$', travel_view.TravelView.travel_get_bound, name='travel-get-bound'),
    url(r'^travels/travel_order/$', travel_view.TravelView.set_travels_order, name='order-travel'),
    url(r'^travels/get-homebound/$', travel_view.TravelView.get_homebound_travel, name='get-homebound-travel'),

    url(r'^get-all-events/$', common_views.EventView.get_all_events, name='get-all-events'),
    url(r'^change-event/$', common_views.EventView.change_event, name='change-event'),
    url(r'^get-events/$', common_views.EventView.get_events, name='get-events'),

    url(r'^menus/$', menu_view.MenuView.as_view(), name='menus'),

    url(r'^menuitems/(?P<pk>[0-9]+)/$', menu_view.MenuItemDetailView.as_view(), name='MenuItemDetails'),
    url(r'^menuitem/delete/$', menu_view.MenuView.delete, name='MenuItemDelete'),
    url(r'^menus/menu_order/$', menu_view.MenuView.set_menus_order, name='order-menu'),
    url(r'^menus/get-parents/$', menu_view.MenuView.get_parents, name='get-parents'),

    url(r'^pages/$', page_view.PageView.as_view(), name='pages'),
    url(r'^pages/edit/(?P<pk>[0-9]+)/$', page_view.PageDetailView.get_page, name='page-edit'),
    url(r'^pages/delete/$', page_view.PageView.delete, name='page-delete'),
    url(r'^pages/(?P<pk>[0-9]+)/$', page_view.PageDetailView.as_view(), name='pages'),
    url(r'^pages/set-element-settings/$', page_view.PageView.set_element_settings, name='set-element-settings'),
    url(r'^pages/get-element-settings/$', page_view.PageView.get_element_settings, name='get-element-settings'),
    url(r'^pages/get-custom-classes/$', page_view.PageView.get_custom_classes, name='get-custom-classes'),
    url(r'^pages/set-custom-classes/$', page_view.PageView.set_custom_classes, name='set-custom-classes'),
    url(r'^pages/get-box-classes/$', page_view.PageView.get_box_classes, name='get-box-classes'),
    url(r'^pages/get-submit-button-name/$', page_view.PageView.get_submit_button_name, name='get-submit-button-name'),
    url(r'^pages/get-pdf-button-name/$', page_view.PageView.get_pdf_button_name, name='get-pdf-button-name'),
    url(r'^pages/get-photo-group-name/$', page_view.PageView.get_photo_group_name, name='get-photo-group-name'),
    url(r'^pages/set-element-html/$', page_view.PageView.set_element_html, name='set-element-html'),
    url(r'^pages/get-element-html/$', page_view.PageView.get_element_html, name='get-element-html'),
    url(r'^pages/delete-element-html/$', page_view.PageView.delete_element_html, name='delete-element-html'),
    url(r'^pages/get-all-rebates/$', page_view.PageView.get_all_rebates, name='get-all-rebates'),
    url(r'^pages/duplicate/$', page_view.PageDetailView.page_duplicate, name='page-duplicate'),

    url(r'^get-managers/$', common_views.EventView.get_managers, name='get-managers'),

    url(r'^printbadge/$', common_views.PrintView.printPage, name='print-badge'),

    url(r'^styles/$', style_view.StyleView.as_view(), name='styles'),

    url(r'^upload-page-image/$', page_view.PageView.upload_image, name='upload-page-image'),

    url(r'^matchings/$', matching.MatchingView.match, name='matching'),

    url(r'^get-page-images/$', page_view.PageDetailView.get_uploaded_images, name='get-page-images'),
    url(r'^get-editor-all-images/$', page_view.PageDetailView.get_editor_all_uploaded_images,
        name='get-editor-all-images'),
    url(r'^upload-image-from-editor/$', page_view.PageDetailView.upload_image_from_editor,
        name='upload-image-from-editor'),
    url(r'^delete-image-from-editor/$', page_view.PageDetailView.delete_image_from_editor,
        name='delete-image-from-editor'),
    url(r'^get-page-with-language/$', page_view.LanguageElement.get_cms_pag_with_language,
        name='get-page-with-language'),

    url(r'^templates/$', template_view.EmailTemplateView.as_view(), name='templates'),
    url(r'^templates/edit/(?P<pk>[0-9]+)/$', template_view.EmailTemplateDetailView.get_template, name='page-edit'),
    url(r'^templates/delete/$', template_view.EmailTemplateView.delete, name='page-delete'),
    url(r'^templates/(?P<pk>[0-9]+)/$', template_view.EmailTemplateDetailView.as_view(), name='pages'),

    url(r'^emails/$', email_view.EmailView.as_view(), name='emails'),
    url(r'^emails-duplicate/$', email_view.EmailView.email_duplicate, name='emails-duplicate'),
    url(r'^emails-delete/$', email_view.EmailView.delete, name='emails-delete'),
    url(r'^emails/(?P<pk>[0-9]+)/$', email_view.EmailDetailView.as_view(), name='emails'),
    url(r'^emails-receivers/(?P<pk>[0-9]+)/$', email_view.EmailReceiversView.as_view(), name='emails-receivers'),
    url(r'^emails-content/(?P<pk>[0-9]+)/$', email_view.EmailContentView.as_view(), name='emails-content'),
    url(r'^emails-content/get-with-lang/$', email_view.EmailContentView.get_lang_email,
        name='emails-content-get-with-lang'),
    url(r'^emails-preview/$', email_view.EmailContentView.show_preview, name='emails-preview'),
    url(r'^emails/search-receiver/$', email_view.EmailReceiversView.search_receivers, name='search-email-receiver'),
    url(r'^emails/change-receiver-status/$', email_view.EmailReceiversView.change_receiver_status,
        name='change-email-receiver-status'),
    url(r'^emails/delete-receiver/$', email_view.EmailReceiversView.delete_receiver, name='delete-email-receiver'),
    url(r'^emails/download-receiver-email/(?P<pk>[0-9]+)/$', email_view.EmailReceiversView.download_email,
        name='download-receiver-email'),
    url(r'^emails/receiver-preview/(?P<pk>[0-9]+)/$', email_view.EmailReceiversView.receiver_preview,
        name='email-receiver-preview'),
    url(r'^emails/send-email/$', email_view.EmailReceiversView.send_email_by_lambda, name='send-email'),
    url(r'^emails/import-filter-receiver/$', email_view.EmailReceiversView.import_filter_receiver,
        name='import-filter-email-receiver'),
    url(r'^emails/import-clipboard-receiver/$', email_view.EmailReceiversView.import_clipboard_receiver,
        name='import-clipboard-email-receiver'),
    url(r'^emails/import-excel-receiver/$', email_view.EmailReceiversView.import_excel_reciever,
        name='import-excel-email-receiver'),

    url(r'^messages/$', message_view.MessageView.as_view(), name='messages'),
    url(r'^messages-duplicate/$', message_view.MessageView.message_duplicate, name='messages-duplicate'),
    url(r'^messages-delete/$', message_view.MessageView.delete, name='messages-delete'),
    url(r'^messages/(?P<pk>[0-9]+)/$', message_view.MessageDetailView.as_view(), name='messages'),
    url(r'^messages-receivers/(?P<pk>[0-9]+)/$', message_view.MessageReceiversView.as_view(),
        name='messages-receivers'),
    url(r'^messages-content/(?P<pk>[0-9]+)/$', message_view.MessageContentView.as_view(), name='messages-content'),
    url(r'^messages-content/get-with-lang/$', message_view.MessageContentView.get_lang_message,
        name='messages-content-get-with-lang'),
    url(r'^messages-preview/$', message_view.MessageContentView.show_preview, name='messages-preview'),
    url(r'^messages/search-receiver/$', message_view.MessageReceiversView.search_receivers,
        name='search-message-receiver'),
    url(r'^messages/change-receiver-status/$', message_view.MessageReceiversView.change_receiver_status,
        name='change-message-receiver-status'),
    url(r'^messages/delete-receiver/$', message_view.MessageReceiversView.delete_receiver,
        name='delete-message-receiver'),
    url(r'^messages/download-receiver-message/(?P<pk>[0-9]+)/$', message_view.MessageReceiversView.download_message,
        name='download-receiver-message'),
    url(r'^messages/receiver-preview/(?P<pk>[0-9]+)/$', message_view.MessageReceiversView.receiver_preview,
        name='message-receiver-preview'),
    url(r'^messages/get-message-receivers/$', message_view.MessageReceiversView.get_total_receiver,
        name='get-message-receivers'),
    url(r'^messages/send-message/$', message_view.MessageReceiversView.send_message, name='send-message'),
    url(r'^messages/import-filter-receiver/$', message_view.MessageReceiversView.import_filter_receiver,
        name='import-filter-message-receiver'),
    url(r'^messages/import-clipboard-receiver/$', message_view.MessageReceiversView.import_clipboard_receiver,
        name='import-clipboard-message-receiver'),
    url(r'^messages/import-excel-receiver/$', message_view.MessageReceiversView.import_excel_reciever,
        name='import-excel-message-receiver'),

    url(r'^reset-your-password/$', reset_password.ResetPasswordREquest.as_view(), name='reset-your-password'),
    url(r'^reset-password/$', reset_password.ResetPassword.as_view(), name='reset-password'),

    url(r'^files/$', file_view.FileView.files, name='files'),
    url(r'^files/newfolder/$', file_view.FileView.newfolder, name='newfolder'),
    url(r'^files/deletefolder/$', file_view.FileView.deletefolder, name='deletefolder'),
    url(r'^files/rename/$', file_view.FileView.rename, name='rename'),
    url(r'^files/fileupload/$', file_view.FileView.fileupload, name='fileupload'),
    url(r'^files/filecopy/$', file_view.FileView.filecopy, name='filecopy'),
    url(r'^files/filecut/$', file_view.FileView.filecut, name='filecut'),
    url(r'^files/getlink/$', file_view.FileView.getlink, name='getlink'),
    url(r'^files/get-all-files/$', file_view.FileView.get_all_files, name='get-all-files'),

    url(r'^language/plugin-language/$', language_view.LanguageView.as_view(), name='plugin-language'),
    url(r'^language/general-language/$', language_view.LanguageView.get_general_language, name='general-language'),
    url(r'^language/date-time-language/$', language_view.LanguageView.get_date_time_language,
        name='date-time-language'),
    url(r'^language/get_preset/$', language_view.LanguageView.get_preset, name='getpreset'),
    url(r'^language/get-general-preset/$', language_view.LanguageView.get_general_preset, name='get-general-preset'),
    url(r'^language/get-date-time-preset/$', language_view.LanguageView.get_date_time_preset,
        name='get-date-time-preset'),
    url(r'^language/add_preset/$', language_view.LanguageView.add_preset, name='addpreset'),
    url(r'^language/rename_preset_name/$', language_view.LanguageView.rename_preset_name, name='renamepresetname'),
    url(r'^language/save_preset/$', language_view.LanguageView.save_preset, name='savepreset'),
    url(r'^language/save-date-time-preset/$', language_view.LanguageView.save_date_time_preset,
        name='save-date-time-preset'),
    url(r'^language/save-general-language/$', language_view.LanguageView.save_general_language,
        name='save-general-language'),
    url(r'^language/delete_preset/$', language_view.LanguageView.delete_preset, name='deletepreset'),

    url(r'^language-default/$', language_default_view.LanguageDefaultView.as_view(), name='language-default'),
    url(r'^language-default/(?P<pk>[0-9]+)/$', language_default_view.DLanguageDetailView.as_view(),
        name='language-default-by-id'),
    url(r'^language-default/edit/$', language_default_view.DLanguageDetailView.save_dlanguage, name='editlanguage'),
    url(r'^language-default/delete/$', language_default_view.DLanguageDetailView.delete_dlanguage,
        name='deletelanguage'),
    url(r'^language-default/source/([0-9]+)/$', language_default_view.LanguageDefaultView.get_lang_key_source,
        name='getlanguagessource'),

    url(r'^deleted/attendees/$', deleted_history.DeletedView.as_view(), name='deleted-attendees'),
    url(r'^deleted/deletedattendees/$', deleted_history.DeletedAttendees.as_view(), name='deleted-attendees-list'),
    url(r'^deleted/attendee-history/$', deleted_history.DeletedView.attendee_history, name='deleted-attendee-history'),

    # Dashboard Statistics Urls
    url(r'^dashboard/pagehit-statistic/$', dashboard.DashboardView.pagehit_statistic, name='pagehit_statistic'),

    url(r'^dashboard/reg-statistic/$', dashboard.DashboardView.reg_statistic, name='reg_statistic'),

    url(r'^dashboard/attendeegroup-statistic/$', dashboard.DashboardView.attendeegroup_statistic,
        name='attendeegroup_statistic'),
    url(r'^dashboard/session-statistic/([0-9]+)$', dashboard.DashboardView.session_statistic,
        name='session_statistic'),
    url(r'^dashboard/filter-statistic/([0-9]+)$', dashboard.DashboardView.filter_statistic,
        name='filter_statistic'),
    url(r'^dashboard/message-statistic/$', dashboard.DashboardView.message_statistic,
        name='message_statistic'),
    url(r'^dashboard/sort-plugin/$', dashboard.DashboardView.sort_plugin,
        name='sort_plugin'),
    url(r'^update-database/$', update_database.UpdateDatabaseView.as_view(),
        name='update-database'),
    url(r'^update-database-request/$', update_database.UpdateDatabaseView.update_database,
        name='update-database-request'),
    url(r'^clean-database-request/$', update_database.UpdateDatabaseView.clean_database,
        name='clean-database-request'),

    url(r'^pages/get-sessions-by-groups/$', page_view.PageView.get_sessions_by_groups, name='get-sessions-by-groups'),
    # url(r'^copy-language/$', common_views.TimeDetailView.language_copy, name='copy-language'),

    url(r'^economy/rebate/$', economy_view.EconomyView.get_rebate_view, name='economy-rebate-view'),
    url(r'^economy/rebate/add-edit-rebate/$', economy_view.EconomyView.add_edit_rebate, name='economy-rebate-add-edit'),
    url(r'^economy/rebate/delete-rebate/$', economy_view.EconomyView.delete_rebate, name='economy-rebate-delete'),
    url(r'^economy/rebates/$', economy_view.EconomyView.get_all_rebates, name='economy-all-rebates'),
    url(r'^economy/payment-settings/$', payment_view.PaymentView.as_view(), name='economy-payment-settings'),
    url(r'^economy/pdf-request/$', attendee_view.AttendeeView.admin_pdf_request, name='economy-admin-pdf-request'),
    url(r'^economy/overview/$', economy_view.EconomyView.get_economy_overview, name='economy-overview'),
    url(r'^economy/overview-report/$', economy_view.EconomyView.get_economy_overview_report, name='economy-overview-report'),
    url(r'^economy/export/$', economy_view.EconomyView.export_all_pdf_view, name='economy-export-all-pdf-view'),
    # url(r'^economy/export/download-all/$', economy_view.EconomyView.economy_export_download, name='economy-export-all-pdf-download'),
    url(r'^economy/export/check-export-status/$', economy_view.EconomyView.economy_export_check_status, name='economy-export-check-status'),
    url(r'^economy/export/download-zipfile/$', economy_view.EconomyView.economy_export_download_zipfile, name='economy-export-download-zipfile'),

]
