INSERT INTO `element_default_lang` (`id`, `type`, `name`, `default_value`, `element_id`, `lang_key`) VALUES
(1, 'notification', 'You have a clash with previously selected session', 'You have a clash with previously selected session', 26, 'notify_clash_session'),
(2, 'notification', 'You are registered for this session', 'You are registered for this session', 26, 'notify_registered_session'),
(3, 'notification', 'You are in Queue for this session', 'You are in Queue for this session', 26, 'notify_queue_session'),
(4, 'notification', 'You have unregistered for this session', 'You have unregistered for this session', 26, 'notify_unregistered_session'),
(5, 'notification', 'This sessions Capacity Full', 'This sessions Capacity Full', 26, 'notify_session_full'),
(6, 'text', 'Title', 'Evaluation', 15, 'evaluation_txt_title'),
(7, 'button', 'Send', 'Send Evaluation', 15, 'evaluation_btn_send'),
(8, 'notification', 'All session are successfully rated.', 'All session are successfully rated.', 15, 'evaluation_notify_session_success'),
(9, 'text', 'Title', 'Messages', 16, 'messages_txt_title'),
(10, 'button', 'Read Archived message', 'Read Archived message', 16, 'messages_btn_read_archived'),
(11, 'button', 'Mark all as read', 'Mark all as read', 16, 'messages_btn_mark_all_read'),
(12, 'notification', 'All message read successfully', 'All message read successfully', 16, 'messages_notify_read_success'),
(13, 'notification', 'message archived successfully', 'message archived successfully', 16, 'messages_notify_archived_success'),
(14, 'text', 'Title', 'Next up', 17, 'nextup_txt_title'),
(15, 'text', 'Title', 'Location list', 18, 'locationlist_txt_title'),
(16, 'text', 'Map to location', 'Map to location', 18, 'locationlist_txt_map_location'),
(17, 'text', 'address', 'address', 18, 'locationlist_txt_address'),
(18, 'text', 'contact', 'contact', 18, 'locationlist_txt_contact'),
(19, 'text', 'Title', 'Session Radio button', 19, 'sessionradiobutton_txt_title'),
(28, 'text', 'Title', 'Session Checkbox', 20, 'sessioncheckbox_txt_title'),
(59, 'text', 'Session Status', 'Session Status', 22, 'hotelreservation_txt_session_status'),
(60, 'text', 'Check-in', 'Check-in', 22, 'hotelreservation_txt_checkin'),
(61, 'text', 'Check-out', 'Check-out', 22, 'hotelreservation_txt_checkout'),
(62, 'text', 'Name', 'Name', 22, 'hotelreservation_txt_name'),
(63, 'text', 'Description', 'Description', 22, 'hotelreservation_txt_description'),
(64, 'text', 'Location', 'Location', 22, 'hotelreservation_txt_location'),
(65, 'text', 'Room buddy', 'Room buddy', 22, 'hotelreservation_txt_room_buddy'),
(66, 'button', 'Add a stay', 'Add a stay', 22, 'hotelreservation_btn_add_stay'),
(67, 'button', 'Remove a stay', 'Remove a stay', 22, 'hotelreservation_btn_remove_stay'),
(68, 'text', 'Hotel name', 'Hotel name', 27, 'th_hotel_name'),
(69, 'text', 'Room Description', 'Room Description', 27, 'th_hotel_room_description'),
(70, 'text', 'Beds', 'Beds', 27, 'th_hotel_beds'),
(71, 'text', 'Check-out', 'Check-out', 27, 'th_hotel_check_out'),
(72, 'text', 'Check-in', 'Check-in', 27, 'th_hotel_check_in'),
(73, 'text', 'Requested room buddy', 'Requested room buddy', 27, 'th_hotel_requested_room_buddy'),
(74, 'text', 'Actual room buddy', 'Actual room buddy', 27, 'th_hotel_actual_room_buddy'),
(75, 'text', 'Location', 'Location', 27, 'th_hotel_location'),
(76, 'text', 'Session', 'Session', 29, 'th_session_session_name'),
(77, 'text', 'Group', 'Group', 29, 'th_session_session_group'),
(78, 'text', 'Description', 'Description', 29, 'th_session_description'),
(79, 'text', 'Start', 'Start', 29, 'th_session_start'),
(80, 'text', 'End', 'End', 29, 'th_session_end'),
(81, 'text', 'Location', 'Location', 29, 'th_session_location'),
(82, 'text', 'Speakers', 'Speakers', 29, 'th_session_speakers'),
(83, 'text', 'Tags', 'Tags', 29, 'th_session_tags'),
(84, 'text', 'Status', 'Status', 29, 'th_session_status'),
(85, 'text', 'Travel name', 'Travel name', 28, 'th_travel_name'),
(86, 'text', 'Group', 'Group', 28, 'th_travel_group'),
(87, 'text', 'Departure city', 'Departure city', 28, 'th_travel_departure_city'),
(88, 'text', 'Arrival city', 'Arrival city', 28, 'th_travel_arrival_city'),
(89, 'text', 'Departure time & date', 'Departure time & date', 28, 'th_travel_departure_time'),
(90, 'text', 'Arrival time & date', 'Arrival time & date', 28, 'th_travel_arrival_time'),
(91, 'text', 'Location', 'Location', 28, 'th_travel_location'),
(92, 'text', 'Description', 'Description', 28, 'th_travel_description'),
(93, 'text', 'Question', 'Question', 30, 'th_question_name'),
(94, 'text', 'Answer', 'Answer', 30, 'th_question_answer'),
(95, 'text', 'Registration date', 'Registration date', 30, 'th_question_registration_date'),
(96, 'text', 'Last update date', 'Last update date', 30, 'th_question_last_update_date'),
(97, 'text', 'Attendee groups', 'Attendee groups', 30, 'th_question_attendee_groups'),
(98, 'text', 'Tags', 'Tags', 30, 'th_question_tags'),
(99, 'text', 'Your email address', 'Your email address', 25, 'request_login_txt_email'),
(100, 'button', 'Request', 'Request', 25, 'request_login_btn_request'),
(101, 'text', 'Validation failed', 'Validation failed', 25, 'request_login_notify_request'),
(102, 'text', 'Email address', 'Email address', 23, 'login_form_txt_email'),
(103, 'text', 'Password', 'Password', 23, 'login_form_txt_password'),
(104, 'text', 'Forgotten your password?', 'Forgotten your password?', 23, 'login_form_txt_forgot_password'),
(105, 'button', 'Login', 'Login', 23, 'login_form_btn_login'),
(106, 'validation_text', 'Validation failed', 'Validation failed', 23, 'login_form_notify_valid_failed'),
(107, 'validation_text', 'Validation failed', 'Validation failed', 22, 'hotelreservation_notify_validation_fail'),
(108, 'validation_text', 'Validation failed', 'Validation failed', 20, 'sessioncheckbox_notify_validation_fail'),
(109, 'text', 'Group', 'Group', 27, 'th_hotel_group'),
(110, 'notification', 'You have a session end', 'You have a new session to evaluate', 15, 'evaluation_notify_socket'),
(111, 'notification', 'Session will start', 'Session {session_name} will be start on {remain_time} minutes', 17, 'nextup_notify_socket_session_will_start'),
(112, 'notification', 'A seat has become available to an activity you"re queueing for but has a time conflict with your previous choice. Would you like to switch to <strong>{session1}</strong> or keep your current choice <strong>{session2}</strong>?', 'A seat has become available to an activity you"re queueing for but has a time conflict with your previous choice. Would you like to switch to <strong>{session1}</strong> or keep your current choice <strong>{session2}</strong>?', 16, 'messages_notify_session_clash'),
(113, 'notification', 'The session <strong>{session}</strong> has been added to your agenda.', 'The session <strong>{session}</strong> has been added to your agenda.', 16, 'messages_notify_session_attend'),
(114, 'text', 'Organizer', 'Organizer', 16, 'messages_txt_organizer'),
(115, 'text', 'Session Conflict', 'Session Conflict', 16, 'message_txt_session_conflict'),
(116, 'button', 'Switch', 'Switch', 16, 'messages_btn_session_conflict_yes'),
(117, 'button', 'Keep', 'Keep', 16, 'messages_btn_session_conflict_no'),
(118, 'text', 'If no answer is received within the next {countdown} the seat is given to the next attendee in Queue.', 'If no answer is received within the next {countdown} the seat is given to the next attendee in Queue.', 16, 'messages_txt_countdown'),
(119, 'notification', 'You have new Notification', 'You have new Notification', 16, 'messages_notify_socket_session'),
(120, 'notification', 'Session is started', 'Session {session_name} is already started', 17, 'nextup_notify_socket_session_started'),
(121, 'notification', 'Login Successfull', 'Login Successfull', 23, 'login_form_notify_successfull'),
(122, 'notification', 'Submit success', 'Submit Successfull', 24, 'submit_button_notify_success'),
(123, 'validation_text', 'Submit Error', 'An Error occurred ', 24, 'submit_button_notify_error'),
(124, 'notification', 'Request Login Activation Url', 'An Email sent to you with activation url', 25, 'request_login_notify_success'),
(125, 'text', 'Email address', 'Email address', 31, 'reset_password_txt_email'),
(126, 'button', 'Send reset instructions', 'Send reset instructions', 31, 'reset_password_btn_send'),
(127, 'validation_text', 'Validation failed', 'Validation failed', 31, 'reset_password_notify_validation'),
(128, 'text', 'New password', 'New password', 32, 'new_password_txt_password'),
(129, 'text', 'Repeat new password', 'Repeat new password', 32, 'new_password_txt_repeat_password'),
(130, 'button', 'Change password', 'Change password', 32, 'new_password_btn_change'),
(131, 'validation_text', 'Validation failed', 'Validation failed', 32, 'new_password_notify_validation'),
(132, 'notification', 'Attendee Registration Successfully', 'Attendee Registration Successfully', 24, 'submit_button_notify_registration_success'),
(133, 'validation_text', 'Email already exists', 'Email already exists', 24, 'submit_button_notify_er_registration_email'),
(134, 'validation_text', 'Something went wrong', 'Something went wrong {error}', 24, 'submit_button_notify_er_registration_failed'),
(135, 'notification', 'Password Changed Successfully', 'Password Changed Successfully', 32, 'new_password_notify_changed'),
(136, 'notification', 'An recovery email has been sent to email', 'An recovery email has been sent to email', 31, 'reset_password_notify_email_send'),
(137, 'text', 'Attendee list intro', 'Attendee list intro', 33, 'attendee_list_txt_title'),
(138, 'button', 'Download spreadsheet', 'Download spreadsheet', 33, 'attendee_list_btn_download_spreadsheet'),
(139, 'notification', 'Spreadsheet Downloaded', 'Spreadsheet Downloaded', 33, 'attendee_list_notify_spreadsheet_download'),
(140, 'text', 'Session Details', 'Session Details', 34, 'sessiondetails_txt_session_details'),
(141, 'text', 'Attending', 'Attending', 34, 'sessiondetails_txt_attending'),
(142, 'text', 'starts', 'starts', 34, 'sessiondetails_txt_starts'),
(143, 'text', 'ends', 'ends', 34, 'sessiondetails_txt_ends'),
(144, 'text', 'Rsvp', 'Rsvp', 34, 'sessiondetails_txt_rsvp'),
(145, 'text', 'Speakers', 'Speakers', 34, 'sessiondetails_txt_speakers'),
(146, 'text', 'Tags', 'Tags', 34, 'sessiondetails_txt_tags'),
(147, 'text', 'Session Group', 'Session Group', 34, 'sessiondetails_txt_session_group'),
(148, 'text', 'Seats Availability', 'Seats Availability', 34, 'sessiondetails_txt_seat_availability'),
(149, 'text', 'Location', 'Location', 34, 'sessiondetails_txt_location'),
(155, 'text', 'Empty', 'Evaluation is Empty', 15, 'evaluation_txt_empty'),
(156, 'text', 'Empty', 'Message is Empty', 16, 'messages_txt_empty'),
(157, 'text', 'Empty', 'Next up is Empty', 17, 'nextup_txt_empty'),
(158, 'text', 'Placeholder Search', 'Search', 18, 'locationlist_txt_placeholder_search'),
(159, 'text', 'Placeholder Search', 'Search', 33, 'attendee_list_txt_placeholder_search'),
(160, 'notification', 'Notification Title Success', 'Success!', 26, 'notify_title_success'),
(161, 'notification', 'Notification Title Warning', 'Warning!', 26, 'notify_title_warning'),
(162, 'notification', 'Notification Title Error', 'Error!', 26, 'notify_title_error'),
(163, 'text', 'Seats Availability Good', 'Good', 34, 'sessiondetails_txt_seat_availability_good'),
(164, 'text', 'X of Y Seats Available', '{X} of {Y} seats available', 34, 'sessiondetails_txt_seat_availability_x_of_y'),
(165, 'text', 'Seats Available', 'seats available', 34, 'sessiondetails_txt_seats_available'),
(166, 'text', 'No Seats Available', 'No seats available', 34, 'sessiondetails_txt_no_seats_available'),
(167, 'text', 'Few Seats Available', 'Few seats available', 34, 'sessiondetails_txt_few_seats_available'),
(168, 'text', 'Queue is Open', 'queue is open', 34, 'sessiondetails_txt_seats_available_queue_is_open'),
(169, 'text', 'Room Buddy Placeholder', 'Select a room buddy', 22, 'hotelreservation_txt_room_buddy_placeholder'),
(170, 'notification', 'Your request is processing, file will be download within few moment', 'Your request is processing, file will be download within few moment', 33, 'attendee_list_notify_download_processing'),
(171, 'text', 'X - Y of Z items', '{X} - {Y} of {Z} items', 33, 'attendee_list_txt_x_y_of_z'),
(172, 'text', 'Archive Messages Intro', 'Archived Messages', 35, 'archive_message_txt_intro'),
(173, 'text', 'Organizer', 'Organizer', 35, 'archive_message_txt_organizer'),
(174, 'text', 'Empty', 'Message is Empty', 35, 'archive_message_txt_empty'),
(175, 'notification', 'This sessions Capacity Full and Queue is not Open', 'This sessions Capacity Full and Queue is not Open', 26, 'notify_session_queue_not_open'),
(176, 'notification', 'You Have Already Attend in this Session', 'You Have Already Attend in this Session', 26, 'notify_session_already_attend'),
(177, 'notification', 'You Have Already in Queue in this Session', 'You Have Already in Queue in this Session', 26, 'notify_session_already_queue'),
(178, 'notification', 'This Session Is not Available', 'This Session Is not Available', 26, 'notify_session_not_available'),
(184, 'text', 'Session Conflict', 'Session Conflict', 35, 'archive_message_txt_session_conflict'),
(185, 'button', 'Yes', 'Yes', 35, 'archive_messages_btn_session_conflict_yes'),
(186, 'button', 'No', 'No', 35, 'archive_messages_btn_session_conflict_no'),
(187, 'text', 'If no answer is received within the next {countdown} the seat is given to the next attendee in Queue.', 'If no answer is received within the next {countdown} the seat is given to the next attendee in Queue.', 35, 'archive_messages_txt_countdown'),
(188, 'text', 'Empty', 'Location is Empty', 18, 'locationlist_txt_empty'),
(189, 'text', 'Empty', 'Session radio is Empty', 19, 'sessionradiobutton_txt_empty'),
(190, 'text', 'Empty', 'Session checkbox is Empty', 20, 'sessioncheckbox_txt_empty'),
(191, 'text', 'Misconfigured', 'Evaluation settings are misconfigured.', 15, 'evaluation_txt_misconfigured'),
(192, 'text', 'Misconfigured', 'Message settings are misconfigured.', 16, 'messages_txt_misconfigured'),
(193, 'text', 'Misconfigured', 'Next Up settings are misconfigured.', 17, 'nextup_txt_misconfigured'),
(194, 'text', 'Misconfigured', 'Location settings are misconfigured.', 18, 'locationlist_txt_misconfigured'),
(195, 'text', 'Misconfigured', 'Session radio settings are misconfigured.', 19, 'sessionradiobutton_txt_misconfigured'),
(196, 'text', 'Misconfigured', 'Session checkbox settings are misconfigured.', 20, 'sessioncheckbox_txt_misconfigured'),
(198, 'text', 'Misconfigured', 'Hotel reservation settings are misconfigured.', 22, 'hotelreservation_txt_misconfigured'),
(199, 'text', 'Misconfigured', 'Login form settings are misconfigured.', 23, 'login_form_txt_misconfigured'),
(200, 'text', 'Misconfigured', 'Submit button settings are misconfigured.', 24, 'submit_button_txt_misconfigured'),
(201, 'text', 'Misconfigured', 'Request login settings are misconfigured.', 25, 'request_login_txt_misconfigured'),
(202, 'text', 'Misconfigured', 'Reset password settings are misconfigured.', 31, 'reset_password_txt_misconfigured'),
(203, 'text', 'Misconfigured', 'New password settings are misconfigured.', 32, 'new_password_txt_misconfigured'),
(204, 'text', 'Misconfigured', 'Attendee list settings are misconfigured.', 33, 'attendee_list_txt_misconfigured'),
(205, 'text', 'Empty', 'Hotel reservation is Empty', 22, 'hotelreservation_txt_empty'),
(206, 'text', 'Empty', 'Attendee list is Empty', 33, 'attendee_list_txt_empty'),
(207, 'text', 'Photo comment label', 'Comment', 36, 'photo_upload_comment_label'),
(208, 'text', 'Photo comment placeholder', 'add comment', 36, 'photo_upload_comment_placeholder'),
(209, 'button', 'Photo Upload Button', 'Upload Photo', 36, 'photo_upload_button'),
(210, 'notification', 'Photo Upload Success', 'Photo Uploaded Successfully', 36, 'photo_upload_notification_success'),
(211, 'validation_text', 'Photo Upload Large Image Error', 'The image you are trying to upload is too large.', 36, 'photo_upload_notification_error_large'),
(212, 'validation_text', 'Photo Upload Small Image Error', 'The image you are trying to upload is too small.', 36, 'photo_upload_notification_error_small'),
(213, 'validation_text', 'Photo Upload General Error', 'Something went wrong. Please try again.', 36, 'photo_upload_notification_error_general'),
(214, 'text', 'Misconfigured', 'Photo Upload settings are misconfigured.', 36, 'photo_upload_txt_misconfigured'),
(215, 'text', 'Misconfigured', 'Photo Gallery settings are misconfigured.', 37, 'photo_gallery_txt_misconfigured'),
(216, 'text', 'Select room buddy', 'Select a room buddy', 22, 'hotelreservation_txt_select_room_buddy'),
(217, 'text', 'No data found', 'No data found', 22, 'hotelreservation_txt_no_data_found'),
(218, 'validation_text', 'Fix date', 'Fix date', 22, 'hotelreservation_notify_fix_date'),
(219, 'validation_text', 'Match previous date', 'Match previous date', 22, 'hotelreservation_notify_match_previous_date'),
(220, 'validation_text', 'Require room selection', 'Require room selection', 22, 'hotelreservation_notify_require_room_selection'),
(221, 'validation_text', 'Require room buddy', 'Require room buddy', 22, 'hotelreservation_notify_require_room_buddy'),
(222, 'validation_text', 'Max stay reached', 'Max stay reached', 22, 'hotelreservation_notify_max_stay_reach'),
(223, 'validation_text', 'Date clash', 'Date clash', 22, 'hotelreservation_notify_date_clash'),
(224, 'validation_text', 'Date is not set', 'Date is not set', 22, 'hotelreservation_date_not_set'),
(225, 'text', 'Please select your {question}', 'Please select your {question}', 30, 'th_question_select_ur_ques'),
(226, 'button', 'Photo Choose Button', 'Upload', 36, 'photo_upload_photo_choose'),
(227, 'text', 'Photo File Name Label', 'Filename:', 36, 'photo_upload_filename'),
(228, 'text', 'Select option text', 'Select', 30, 'th_question_select_option'),
(229, 'text', 'Photo gallery pagination text', 'Showing {X} to {Y} of {Z} photos', 37, 'photo_gallery_pagination_text'),
(230, 'text', 'Logout message text', 'You''ve been logged out. Click here to go to the start page', 38, 'logout_message_text'),
(231, 'button', 'Logout back button', 'Go To Start Page', 38, 'logout_back_button'),
(232, 'text', 'Comment label text', 'Comment', 37, 'photo_gallery_comment_text'),
(233, 'text', 'Uploader label text', 'Uploader', 37, 'photo_gallery_uploader_text'),
(234, 'text', 'No Photo exist text', 'No Photo exist', 37, 'photo_gallery_no_photo_exist_text'),
(235, 'text', 'Text for pagination Previous', 'Previous', 37, 'photo_gallery_previous_text'),
(236, 'text', 'Text for pagination Next', 'Next', 37, 'photo_gallery_next_text'),
(237, 'validation_text', 'Room validation message', 'Room is not available.', 22, 'hotelreservation_notify_room_validation_msg'),
(238, 'notification', 'Attendee update success message', 'Attendee Updated Successfully.', 24, 'submit_button_notify_update_success'),
(239, 'validation_text', 'Attendee update fail message', 'Attendee Update Failed.', 24, 'submit_button_notify_update_fail'),
(240, 'validation_text', 'Message Archive failed', 'Message Archive failed', 16, 'messages_notify_validation_failed'),
(241, 'validation_text', 'Session rated failed.', 'Session rated failed.', 15, 'evaluation_notify_validation_failed'),
(242, 'validation_text', 'Validation failed', 'Validation failed', 19, 'sessionradiobutton_notify_validation_fail'),
(243, 'button', 'Test', 'Test', 39, 'multiple_registration_add_attendee_test'),
(244, 'text', 'Current number of attendees Text', 'Current number of attendees', 39, 'multiple_registration_current_no_of_attendees'),
(245, 'button', 'Edit Button', 'Edit', 39, 'multiple_registration_edit_button'),
(246, 'button', 'Delete Button', 'Delete', 39, 'multiple_registration_delete_button'),
(247, 'text', 'Not yet registered Text', 'Not yet registered', 39, 'multiple_registration_not_yet_registered'),
(248, 'button', 'Add attendee Button', 'Add an attendee', 39, 'multiple_registration_add_attendee'),
(249, 'text', 'Misconfigured Text', 'Multiple registration settings are Misconfigured', 39, 'multiple_registration_misconfigured'),
(250, 'validation_text', 'Validation failed', 'Validation failed', 39, 'multiple_registration_validation_fail'),
(251, 'notification', 'Attendee registration time expire notification', 'Your temporary session has been expired.', 26, 'notify_attendee_registration_time_expire'),
(252, 'validation_text', 'Error', 'Something Went wrong. Please try again', 39, 'multiple_registration_failed'),
(253, 'notification', 'Success', 'All attendee Register successfully', 39, 'multiple_registration_success'),
(254, 'text', 'Column Attendee group', 'Attendee group', 39, 'multiple_registration_group_column'),
(255, 'text', 'Column Attendee Actions', 'Actions', 39, 'multiple_registration_actions_column'),
(256, 'text', 'Order Owner', 'Order Owner', 39, 'multiple_registration_text_order_owner'),
(257, 'text', 'Attendee', 'Attendee', 39, 'multiple_registration_text_attendee'),
(258, 'text', 'Session Cost', 'Cost', 34, 'sessiondetails_txt_session_cost'),
(259, 'text', 'Session Cost Excluding Vat', '(excl. vat {X})', 34, 'sessiondetails_txt_session_cost_excl_vat'),
(260, 'text', 'Session Cost Including Vat', '(incl. vat {X})', 34, 'sessiondetails_txt_session_cost_incl_vat'),
(270, 'text', 'Economy Order Table', 'Order Table', 41, 'economy_txt_order_table'),
(271, 'text', 'Economy Order Number', 'Order Number', 41, 'economy_txt_order_number'),
(272, 'text', 'Economy Status', 'Status', 41, 'economy_txt_status'),
(273, 'text', 'Economy Due Date', 'Due', 41, 'economy_txt_due_date'),
(274, 'text', 'Economy Cost Excluding VAT', 'Cost excl. VAT', 41, 'economy_txt_cost_excl_vat'),
(275, 'text', 'Economy Cost Including VAT', 'Cost incl. VAT', 41, 'economy_txt_cost_incl_vat'),
(276, 'text', 'Economy Rebate Amount', 'Rebate Amount', 41, 'economy_txt_rebate_amount'),
(277, 'text', 'Economy Amount', 'Amount', 41, 'economy_txt_amount'),
(278, 'text', 'Economy VAT', 'VAT', 41, 'economy_txt_vat'),
(279, 'text', 'Economy Amount', 'Amount', 41, 'economy_txt_amount'),
(280, 'text', 'Economy Grand Total', 'Grand Total', 41, 'economy_txt_grand_total'),
(281, 'text', 'Economy Balance Table', 'Balance Table', 41, 'economy_txt_balance_table'),
(282, 'text', 'Economy Date & time', 'Date & time', 41, 'economy_txt_data_and_time'),
(283, 'text', 'Economy Link to Invoice / Receipt', 'Link to Invoice / Receipt', 41, 'economy_txt_link_to_invoice_or_receipt'),
(284, 'button', 'Economy Invoice Download Button', 'Download', 41, 'economy_txt_invoice_download_button'),
(285, 'text', 'Economy Invoice created', 'Invoice created', 41, 'economy_txt_invoice_created'),
(286, 'text', 'Economy Invoice settled', 'Invoice settled', 41, 'economy_txt_invoice_settled'),
(287, 'text', 'Economy Credit invoice', 'Credit invoice', 41, 'economy_txt_credit_invoice'),
(288, 'text', 'Economy Order balance', 'Order balance', 41, 'economy_txt_order_balance'),
(289, 'text', 'Economy Misconfigured', 'Economy settings are Misconfigured', 41, 'economy_txt_misconfigured'),
(290, 'validation_text', 'Validation failed', 'Validation failed', 41, 'economy_notify_validation_fail'),
(291, 'text', 'Economy Status Open', 'Open', 41, 'economy_txt_status_open'),
(292, 'text', 'Economy Status Pending', 'Pending', 41, 'economy_txt_status_pending'),
(293, 'text', 'Economy Status Paid', 'Open', 41, 'economy_txt_status_paid'),
(294, 'text', 'Economy Status Cancelled', 'Cancelled', 41, 'economy_txt_status_cancelled'),
(295, 'button', 'Economy Place Order Button', 'Place Order', 41, 'economy_txt_place_order_button'),
(296, 'text', 'Economy Empty', 'Economy settings are Empty', 41, 'economy_txt_empty'),
(297, 'notification', 'Order status change message', 'Order status is changed Open to Pending successfully', 41, 'economy_notify_order_status_change'),
(298, 'text', 'Title', 'Session Agenda', 42, 'session_agenda_txt_title'),
(299, 'text', 'Show my sessions', 'Show my sessions only', 42, 'session_agenda_txt_show_my_sess'),
(310, 'button', 'Today Button', 'Today', 42, 'session_agenda_btn_today'),
(311, 'button', 'Subscribe to my sessions', 'Subscribe to my sessions', 42, 'session_agenda_btn_subscribe_sessions'),
(319, 'text', 'Misconfigured', 'Session Agenda settings are misconfigured.', 42, 'session_agenda_txt_misconfigured'),
(320, 'text', 'Column Session Group', 'Session Group', 42, 'session_agenda_txt_column_session_group'),
(321, 'text', 'Column Date', 'Date', 42, 'session_agenda_txt_column_date'),
(322, 'text', 'Column Time', 'Time', 42, 'session_agenda_txt_column_time'),
(323, 'text', 'Column Event', 'Event', 42, 'session_agenda_txt_column_event'),
(324, 'text', 'Placeholder Search', 'Search', 42, 'session_agenda_txt_placeholder_search'),
(330, 'validation_text', 'You need to have at least one track selected', 'You need to have at least one track selected', 42, 'session_agenda_notify_track'),
(331, 'button', 'Prev Button', 'Prev', 42, 'session_agenda_btn_prev'),
(332, 'button', 'Next Button', 'Next', 42, 'session_agenda_btn_next'),
(333, 'text', 'Empty', 'Nothing to display', 42, 'session_agenda_txt_empty'),
(334, 'text', 'Location Details', 'Location Details', 18, 'locationlist_txt_location_details'),
(335, 'text', 'Attendee Details', 'Attendee Details', 30, 'th_question_attendee_details'),
(336, 'text', 'Session Details Status Attending', 'Attending', 34, 'sessiondetails_txt_status_attending'),
(337, 'text', 'Session Details Status In Queue', 'In Queue', 34, 'sessiondetails_txt_status_in_queue'),
(338, 'text', 'Session Details Status Time Conflict', 'Time Conflict', 34, 'sessiondetails_txt_status_time_conflict'),
(339, 'text', 'Session Details Status Full', 'Full', 34, 'sessiondetails_txt_status_full'),
(340, 'text', 'Session Details Status Not Attending', 'Not Attending', 34, 'sessiondetails_txt_status_not_attending'),
(341, 'text', 'Session Details Status Deciding', 'Deciding', 34, 'sessiondetails_txt_status_deciding'),
(342, 'text', 'RSVP deadline passed', 'RSVP deadline passed', 34, 'sessiondetails_txt_status_rsvp_passed'),
(343, 'text', 'Queue Open', 'Queue Open', 34, 'sessiondetails_txt_status_queue_open'),
(344, 'text', 'Queue Close', 'Queue Close', 34, 'sessiondetails_txt_status_queue_close'),
(345, 'text', 'Currency', 'SEK', 41, 'economy_txt_currency'),
(346, 'button', 'Settle Order', 'Settle Order', 41, 'economy_btn_settle_order'),
(347, 'button', 'Change order status', 'Change order status', 41, 'economy_btn_change_order_status'),
(348, 'text', 'Attendee text for group order', 'Attendee:', 41, 'economy_txt_attendee'),
(349, 'text', 'Date Of Transaction', 'Date Of Transaction', 41, 'economy_txt_date_of_transaction'),
(350, 'text', 'Card Number', 'Card Number', 41, 'economy_txt_card_number'),
(351, 'text', 'Transaction Id', 'Transaction Id', 41, 'economy_txt_transaction_id'),
(352, 'text', 'Payment Information', 'Payment Information', 41, 'economy_txt_payment_information'),
(353, 'text', 'Amount Due in order table', 'Amount Due', 41, 'economy_txt_amount_due'),
(354, 'text', 'Costs in order table', 'Costs', 41, 'economy_txt_order_table_costs'),
(355, 'text', 'Activities in balance table', 'Activities', 41, 'economy_txt_balance_table_activities'),
(356, 'text', 'Total Vat', 'Total', 41, 'economy_txt_order_table_total_vat'),
(357, 'text', 'Economy Grand Total - Invoice', 'Grand Total', 41, 'economy_txt_grand_total_invoice'),
(358, 'text', 'Economy Grand Total - Credit Invoice', 'Grand Total', 41, 'economy_txt_grand_total_credit_invoice'),
(360, 'text', 'Counting column header', 'Sl.', 33, 'attendee_list_txt_counting_column_header'),
(361, 'text', 'Misconfigured', 'Pdf button settings are misconfigured.', 43, 'pdf_button_txt_misconfigured'),
(362, 'text', 'Attendee Logout Button Text', 'Log out', 44, 'attendee_logout_txt_button'),
(363, 'text', 'Cost Excluding VAT', 'Cost excl. VAT', 22, 'hotelreservation_txt_cost_excl_vat'),
(364, 'text', 'Cost Including VAT', 'Cost incl. VAT', 22, 'hotelreservation_txt_cost_incl_vat'),
(365, 'text', 'VAT %', 'VAT %', 22, 'hotelreservation_txt_vat_percentage'),
(366, 'text', 'VAT Amount', 'VAT Amount', 22, 'hotelreservation_txt_vat_amount'),
(367, 'text', 'No hotel text', 'no hotel', 22, 'hotelreservation_txt_no_hotel_text'),
(368, 'text', 'Max buddy selected text', 'You can only select {X} item', 22, 'hotelreservation_txt_max_buddy_selected'),
(369, 'text', 'Input is too short in room-buddy textbox', 'Please enter 1 or more characters', 22, 'hotelreservation_txt_input_too_short'),
(370, 'notification', 'Session Expire Notification', 'You have been idle for too long and have been logged out. Click Okay to reload the page.', 26, 'notify_session_expire'),
(371, 'button', 'Economy Invoice Download Button Next to Settle Order Button', 'Download Invoice', 41, 'economy_invoice_download_button_next_settle_order'),
(372, 'button', 'Economy Receipt Download Button Next to Settle Order Button', 'Download Receipt', 41, 'economy_receipt_download_button_next_settle_order'),
(373, 'text', 'Total Attendee Text', 'Total', 33, 'attendee_list_txt_total_attendee_count'),
(374, 'notification', 'Notification Title Notify', 'Notification!', 26, 'notify_title_notify'),
(375, 'text', 'Image details text', 'Image Details', 37, 'photo_gallery_image_details_text'),
(376, 'text', 'Economy Orders Empty', 'You do not have an order associated with you or your order is handled by someone else.', 41, 'economy_order_empty'),
(377, 'text', 'Economy Rebate Text With', 'With', 41, 'economy_txt_rebate_with'),
(378, 'text', 'Economy Rebate Text Rebate', 'rebate', 41, 'economy_txt_rebate_rebate'),
(379, 'text', 'Session Details Link', 'Read more', 34, 'sessiondetails_txt_session_detail_link'),
(380, 'text', 'Resest password header', 'Retrieve Password', 31, 'reset_password_txt_header'),
(381, 'text', 'Resest password message', 'There are multiple instances of your email, please select one below', 31, 'reset_password_txt_message'),
(382, 'text', 'Resest password Column First name', 'First name', 31, 'reset_password_txt_th_first_name'),
(383, 'text', 'Resest password Column Last name', 'Last name', 31, 'reset_password_txt_th_last_name'),
(384, 'text', 'Resest password Column Event', 'Event', 31, 'reset_password_txt_th_event'),
(385, 'text', 'Resest password Column Select', 'Select', 31, 'reset_password_txt_th_select'),
(386, 'button', 'Resest password Select Event', 'Select', 31, 'reset_password_btn_select_event')
ON DUPLICATE KEY UPDATE
id = VALUES(id),
type = VALUES(type),
name = VALUES(name),
default_value= VALUES(default_value),
element_id= VALUES(element_id),
lang_key= VALUES(lang_key);